config/routes.rb
Rails.application.routes.draw do
  post 'messages/create'
  get 'users/index'
  devise_for :users
  root 'user_pages#home'
  delete 'users/block'
  get 'users/invites'
  delete 'users/destroy'
  get 'users/accept_request'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invite.rb
class Invite < ApplicationRecord
  
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_user!

  def logged_in_user
      unless user_signed_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
  protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :terms_and_conditions, :avatar])
   devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :password, :password_confirmation, :email, :dob, :avatar])
   devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:login, :password, :password_confirmation)
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @user = User.find_by(id: msg_params[:reciever_id])
    @user.update(archived: false) if @user.archived
    @message = Message.new(msg_params)
    @message.sender_id = current_user.id
    @message.save
    @chatlist = Message.where(sender_id:current_user).or(Message.where(reciever_id:current_user)).order(created_at: :ASC)
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private
  
  def msg_params
    params.require(:message).permit(:msg_body, :reciever_id)
  end
end

app/controllers/user_pages_controller.rb
class UserPagesController < ApplicationController
  def home
    users = User.where.not(id: current_user)
    @friend = Invite.where(status: 'accepted', invited_by: current_user)
    @friends = users.where(id: @friend.pluck(:invited_to), archived: false, block: false)
    @chatlist = Message.where(sender_id:current_user).or(Message.where(reciever_id:current_user)).order(created_at: :ASC)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
    @invites = Invite.where(invited_to: current_user.id)
    @invitedusers = User.where(id: @invites.pluck(:invited_by))
  end

  def invites
    if Invite.where(invited_to: params[:invited_to], invited_by: current_user.id).present?
      flash[:danger] = "Already Invited"
      redirect_to users_index_path
    else
      invite = Invite.new
      invite.invited_to = params[:invited_to]
      invite.invited_by = current_user.id
      invite.invited = true
      invite.save!
      flash[:success] = "Invite has been sent"
      redirect_to users_index_path
    end
  end

  def accept_request
    @invite = Invite.find_by(invited_by: params[:user_id], invited_to: current_user.id)
    if @invite.update(status: "accepted")
      respond_to do |format|
      format.html { redirect_to users_index_path }
      format.js
      end
    else
        flash[:danger] = "Something went to wrong!"
        redirect_to users_index_path
    end
  end
  def destroy
    user = User.find_by(id: params[:user_id])
    user.update(archived: true)
    flash[:success] = "User Archieved"
    redirect_to root_path
  end
  def block
    user = User.find_by(id: params[:user_id])
    user.update(block: true)
    flash[:success] = "User Blocked"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color:green">
  <div class="container">
    <% if user_signed_in? %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
              aria-expanded="false">
          <span class="sr-only"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
    </div>
    <ul class="nav navbar-nav navbar-left collapse navbar-collapse" >
      <li><%= image_tag(current_user.avatar.url, width: "50 %",height: "50 %", class:"profileimg") %></li>
      <% current_user.first_name ||= current_user.username  %>
        <li><%= link_to "#{current_user.first_name} #{current_user.last_name}", root_path, id: "logo" %></li>
    <% else %>
      <%= link_to "E-chat", root_path, id: "logo" %>
    <% end %>
  </ul>
</nav>
    <nav>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>        
          <li><%= link_to "Requests", users_index_path, style:"color:white" %></li>
          <li><%= link_to "Settings", edit_user_registration_path(current_user), style:"color:white"  %></li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, style:"color:white" %>
          </li>
        <% else %>
          <li><%= link_to "Register", new_user_registration_path, style:"color:white" %></li>
          <li><%= link_to "Log in", new_user_session_path, style:"color:white" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Echat</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="content-box" style="width: 80%">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_chats.html.erb
<div class="col-xs-12 col-md-12 div_frends_list overflow-auto msglist"  >
  <% @chatlist.where("sender_id =? or reciever_id =?", user.id, user.id).each do |msg| %>
    <div class="col-xs-12 col-md-12 margin-left">
      <% if msg.reciever_id == current_user.id && msg.sender_id == user.id && msg.msg_body != ""  %>
           <p class="msgboxreciever"><%=  "[ #{msg.created_at.strftime("%I:%M %p")}]"  %>
           <% user.first_name ||= user.username  %>
           <%= "#{msg.msg_body}" %></p>
      <% end %>
    </div>
  <div class="col-xs-12 col-md-12 margin-right">
    <% if msg.reciever_id == user.id && msg.sender_id == current_user.id && msg.msg_body != ""  %>
         <p class="msgboxsender"><%=  " [ #{msg.created_at.strftime("%I:%M %p")}]" %>
      <% current_user.first_name ||= current_user.username  %>
      <%= "#{msg.msg_body}" %></p>
    <% end %>
  </div>
  <% end %>
</div>

app/views/messages/_message.html.erb
<div id="msgform">
<%= form_with scope: :message, class:"chat_window", url: messages_create_path, remote: true do |form| %>

    <%= form.hidden_field :reciever_id, value: user_id %>
    <%= form.text_area :msg_body, class: 'form-control' %>
</br>
    <%= form.submit "Sent", class: "btn btn-primary" %>
<% end %>
</div>

app/views/messages/create.js.erb
$("#divchatrow-<%= @user.id %>").html("<%= escape_javascript(render(partial: 'messages/chats', locals: {user: @user}) ) %>");

app/views/user_pages/_invite.html.erb
<% @friend.each do |user| %>
   <div class="row">
     <div class="col-xs-9 col-md-4">
       <%= image_tag(user.avatar.url, width: "50",height: "50", class:"profileimg") %>
       <% user.first_name ||= user.username  %>
         <%= "#{user.first_name} #{user.last_name}"%>
      </div>
   </div>
   <br/>
 <% end %>

app/views/user_pages/_msg_tab.html.erb
<div class ="row chat_row">
  <% if @friends.any?  %>
    <% @friends.each do |user| %>
      <div class="row" >
        <div class="col-xs-12 col-md-3 div_frends_list overflow-auto user">
          <%= image_tag(user.avatar.url, width: "50",height: "50", class:"profileimg") %>
            <% user.first_name ||= user.username  %>
              <%= "#{user.first_name} #{user.last_name}" %>
        </div>
        <div class="col-xs-12 col-md-6 div_frends_list overflow-auto chat hidden">
          <div class="row" id="header_user_profile">
            <div class="col-xs-12 col-md-12 div_frends_list overflow-auto" >
              <%= image_tag(user.avatar.url, width: "50",height: "50", class:"profileimg") %>
              <% user.first_name ||= user.username  %>
                <%= "#{user.first_name} #{user.last_name}" %>
            </div>
            <div id="divchatrow-<%= user.id %>">
              <%= render partial: "messages/chats", locals: {user: user} %>
            </div>
              <%= render partial: "messages/message", locals: {user_id: user.id, current_user: current_user.id}, style:"width:100%" %>
          </div>
        </div>
        <div class="col-xs-12 col-md-3  profile hidden" id="div_frends_list">
          <%= image_tag(user.avatar.url, width: "200", height: "200", class:"userimg profileimg")%>
            <% user.first_name ||= user.username %>
          <h3 class="username"><%= "#{user.first_name} #{user.last_name}"%></h3>
          <h5 class="useremail"><span class="glyphicon glyphicon-envelope"></span> <%= "#{user.email}"%></h5>
          <h5 class="userdob"><span class="glyphicon glyphicon-candle"></span> <%= "#{user.dob}"%></h5>
          <h5 class="userarchive">
            <% if user.archived == false %>
              <%= link_to '<button type="button" class="btn btn-md btn-default">Archiev</button>'.html_safe, users_destroy_path(user_id: user.id), method: :delete, data: { confirm: "You sure?" }%>
            <% end %>
            <%= link_to '<button type="button" class="btn btn-md btn-default">Block</button>'.html_safe, users_block_path(user_id: user.id), method: :delete, data: { confirm: "You sure?" }%>
          </h5>
        </div>
      </div>
    <% end %>
    <% else %>
      <div class = "col-md-12 center">
        <% current_user.first_name ||= current_user.username  %>
        <h2>You don't have any friend</h4>
        <h3>Welcome <%= "#{current_user.first_name} #{current_user.last_name}"  %> </h3>
        <h4>Find your friend</h4>
          <%= image_tag(current_user.avatar.url, width: "200", height: "200")%>
      </div>
    <% end %>
  </div>

app/views/user_pages/home.html.erb
<% if user_signed_in? %>
  <%= render 'msg_tab'%>
  </br>
  <% else %>
    <h2>E-chat is a platform of connect to your friends and family.</h2>
    <br><br>
    <p>
      <%= link_to "Create Account", new_user_registration_path, class: "btn  btn-primary", id: "btnsignup" %>
      <%= link_to "Sign in?", new_user_session_path, class: "btn  btn-primary", id: "btnsignup" %>
    </p>
<% end %>

app/views/users/_accept_reject_button.html.erb
<div class="col-xs-3 col-md-4" id="request_buttons_<%= user_id %>">
  <% if Invite.find_by(status: "accepted", invited_by: user_id, invited_to: current_user.id) %>
    <span class="btn btn-primary" >Friend</span>
   <% else %>
   <%= link_to "<button class='btn btn-primary' aria-hidden='true'>Accept</button>".html_safe,
    users_accept_request_path(user_id: user_id),  method: :get, remote: true %>
  <% end %>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.username, user %>
</li>

app/views/users/accept_request.js.erb
$("#request_buttons_<%= @invite.invited_by %>").html("<%= escape_javascript(render(partial: 'users/accept_reject_button', locals: {user_id: @invite.invited_by})) %>");

app/views/users/index.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class = "col-md-12">
      <ul class="nav nav-tabs">
        <li class="nav-item active" style="width:50%">
          <a class="nav-link" data-toggle="tab" href="#explore"><strong>Explore</strong></a>
        </li>
        <li class="nav-item" style="width:50%">
          <a class="nav-link" data-toggle="tab" href="#invites"><strong>Invites</strong></a>
        </li>
      </ul>
      <div class="tab-content" id = "tabs">
        <div id="explore" class="container tab-pane active"><br>
          <% @users.each do |user| %>
             <div class="row">
              <div class="col-xs-9 col-md-4">
                <%= image_tag(user.avatar.url, width: "50",height: "50", class:"profileimg") %>
                <% user.first_name ||= user.username  %>
                 <%= "#{user.first_name} #{user.last_name}"%>
              </div>
              <div class="col-xs-3 col-md-4">
                <%= link_to "Invite", users_invites_path(invited_to: user.id), class: "btn  btn-primary", id: "btnsignup" %>
              </div>
             </div>
             <br/>
           <% end %>
         </div>
         <div id="invites" class="container tab-pane"><br>
          <% @invitedusers.each do |user| %>
            <div class="row">
              <div class="col-xs-9 col-md-4">
                <%= image_tag(user.avatar.url, width: "50",height: "50", class:"profileimg") %>
                  <% user.first_name ||= user.username  %>
                    <%= "#{user.first_name} #{user.last_name} "%>
              </div>
              <%= render partial: 'accept_reject_button', locals:{user_id: user.id}%>
            </div>
            <br/>
          <% end %>
         </div>
      </div>
    </div>
  </div>
<% else %>
  <h2>E-chat is a platform of connect to your friends and family.</h2>
  <p>
  <br>
  <br>
    <%= link_to "Create Account", new_user_registration_path, class: "btn  btn-primary", id: "btnsignup" %>
  </p>
<% end %>